describe('Adding location',()=>
{
    it('Adding',()=>
    {
        cy.visit('http://hrms219.sphinxworldbiz.com:2045/LoginNew.aspx')
        cy.get('#txtUsername').type('administrator')
        cy.get('#txtPassword').type('Sphinx@789$')
        cy.get('#btnSubmit').click()
        cy.get('.gallaryIcon').scrollIntoView({duration:2000})
        cy.get('.icon-dashboard').trigger('mouseover')
        cy.get ('#li82').click()
        cy.get('#li34').click()
        cy.get('#li21').click()
        cy.get('#MenuContainer > ul > :nth-child(3) > a').click()
        cy.get('.add-emp-plus').click()
        cy.get('#ddl_company').select('Vipro')
       cy.get('#div_CompanyBranch > :nth-child(1) > .form-group > :nth-child(2)').should('be.visible').type('Hyderabad')
       cy.get('#txt_Address').type('Andhra pradesh')
       cy.get('#txt_city').type('kurnool')
       cy.get('#ddl_country').select('INDIA')
       cy.get('#txt_ZipCode').type('518006')
       cy.get('#ddl_state').select('Goa')
       cy.get('#ddl_TimeZone').select('Angola')
       cy.get('#txt_latitude').type('90')
       cy.get('#txt_longitude').type('180')
       cy.get('#txt_radius').type('100')
       cy.get('#ddl_Status').select('Active')
       cy.get('.add-body-buttons > #btn_Save').click()
    })
})